### ISSUE TITLE
Establecer relaciones y mejoras en Especialidad

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/turnero2023spring#24]
**Tareas:**

1. **Establecer relaciones en las entidades con `@ManyToOne`:**

   - Identificar y definir relaciones `@ManyToOne` en la entidad `Especialidad` donde sea necesario.

2. **Implementar método `exists` en el servicio:**

   - Agregar un método `exists` en el servicio para verificar la existencia de objetos en la base de datos en función de un ID proporcionado.

3. **Realizar pruebas exhaustivas del servicio con Postman:**

   - Realizar pruebas completas del servicio utilizando Postman para garantizar su correcto funcionamiento. Esto incluye:
     - Prueba POST para agregar nuevos objetos.
     - Prueba PUT para actualizar objetos existentes.
     - Prueba DELETE para eliminar objetos.
     - Prueba GET para recuperar todos los objetos.
     - Prueba GET para recuperar un objeto por su ID.

**Fecha límite:** 22 de Septiembre

**Evidencia:**

Por favor, asegúrate de proporcionar evidencia que respalde la realización exitosa de estas tareas antes de la fecha límite mencionada.

**Comment by RoxanaArenas** [comment]
![image](https://github.com/ahumadamob/turnero2023spring/assets/83459444/755bab27-ee2f-4e1c-86dc-9a10e0f73b12)

**Comment by RoxanaArenas** [comment]
![image](https://github.com/ahumadamob/turnero2023spring/assets/83459444/b315222b-1528-4eb1-bf6b-bd89e8264d6b)

**Comment by RoxanaArenas** [comment]
![image](https://github.com/ahumadamob/turnero2023spring/assets/83459444/34706ffd-c7d9-4e7c-8796-c68e6c750837)

**Comment by RoxanaArenas** [comment]
![image](https://github.com/ahumadamob/turnero2023spring/assets/83459444/091a76c8-cac0-4768-a62e-dde2d4844ba2)
