### ISSUE TITLE
Establecer relaciones y mejoras en Profesional

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/turnero2023spring#27]
**Tareas:**

1. **Establecer relaciones en las entidades con `@ManyToOne`:**

   - Identificar y definir relaciones `@ManyToOne` en la entidad `` donde sea necesario.

2. **Implementar método `exists` en el servicio:**

   - Agregar un método `exists` en el servicio para verificar la existencia de objetos en la base de datos en función de un ID proporcionado.

3. **Realizar pruebas exhaustivas del servicio con Postman:**

   - Realizar pruebas completas del servicio utilizando Postman para garantizar su correcto funcionamiento. Esto incluye:
     - Prueba POST para agregar nuevos objetos.
     - Prueba PUT para actualizar objetos existentes.
     - Prueba DELETE para eliminar objetos.
     - Prueba GET para recuperar todos los objetos.
     - Prueba GET para recuperar un objeto por su ID.

**Fecha límite:** 22 de Septiembre

**Evidencia:**

Por favor, asegúrate de proporcionar evidencia que respalde la realización exitosa de estas tareas antes de la fecha límite mencionada.

**Comment by EmilianoBarroso** [comment]
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/c7da6365-7b80-48be-a118-201dfabf09a5)

**Comment by EmilianoBarroso** [comment]
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/2d45132b-fee7-4925-82b6-7aa82f508894)

**Comment by EmilianoBarroso** [comment]
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/0613297b-1601-47c5-8391-85eae9327053)

**Comment by EmilianoBarroso** [comment]
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/71fa4883-712a-4655-917c-af195ab9beba)

**Comment by EmilianoBarroso** [comment]
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/6f9d9904-42e2-40a5-9375-e5842944e077)

**Comment by EmilianoBarroso** [comment]
Nueva Prueba (Prueba GET para recuperar todos los objetos)
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/ab666254-3743-410e-b4cf-8a3ba5cfc7b2)

**Comment by EmilianoBarroso** [comment]
Nueva Prueba (Prueba GET para recuperar un objeto por su ID)
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/28e317a5-1ef5-4152-8425-f6e815d3247b)

**Comment by EmilianoBarroso** [comment]
Nueva Prueba (Prueba DELETE para eliminar objetos.)
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/1230bcd5-232f-4dc5-8da9-e1ac3d6d4bd5)

**Comment by EmilianoBarroso** [comment]
Nueva Prueba (Prueba POST para agregar nuevos objetos)
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/ef07802a-6b04-4b18-8402-4a6e6c3a5fc4)

**Comment by EmilianoBarroso** [comment]
Nueva Prueba (Prueba PUT para actualizar objetos existentes)
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/06be8369-6531-4d6a-8338-09666c22c9cb)
