### ISSUE TITLE
Establecer relaciones y mejoras en Sala

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/turnero2023spring#28]
Establecer relaciones y mejoras en Sala

**Tareas:**

1. **Establecer relaciones en las entidades con `@ManyToOne`:**

   - Identificar y definir relaciones `@ManyToOne` en la entidad `Sala` donde sea necesario.

2. **Implementar método `exists` en el servicio:**

   - Agregar un método `exists` en el servicio para verificar la existencia de objetos en la base de datos en función de un ID proporcionado.

3. **Realizar pruebas exhaustivas del servicio con Postman:**

   - Realizar pruebas completas del servicio utilizando Postman para garantizar su correcto funcionamiento. Esto incluye:
     - Prueba POST para agregar nuevos objetos.
     - Prueba PUT para actualizar objetos existentes.
     - Prueba DELETE para eliminar objetos.
     - Prueba GET para recuperar todos los objetos.
     - Prueba GET para recuperar un objeto por su ID.

**Fecha límite:** 22 de Septiembre

**Evidencia:**

Por favor, asegúrate de proporcionar evidencia que respalde la realización exitosa de estas tareas antes de la fecha límite mencionada.

**Comment by facuEgarrat** [comment]
![Captura de pantalla 2023-09-25 211854](https://github.com/ahumadamob/turnero2023spring/assets/136384242/5d0ceab3-30d0-41a2-9847-cd5ab0bbe52c)
![Captura de pantalla 2023-09-25 211711](https://github.com/ahumadamob/turnero2023spring/assets/136384242/d2654e70-0009-4046-8489-0d31579ba313)
![Captura de pantalla 2023-09-25 211801](https://github.com/ahumadamob/turnero2023spring/assets/136384242/51e91de3-684f-4ac0-b3ef-40dd75f3f01b)
![Captura de pantalla 2023-09-25 211829](https://github.com/ahumadamob/turnero2023spring/assets/136384242/07b96a97-f03f-4091-92e5-6d522eb2ff2d)
