### ISSUE TITLE
Mejoras en la entidad: Profesional

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/turnero2023spring#37]
**Entidad**

Verificar que en tu entidad asignada tenga las relaciones `@ManyToOne` correspondientes

**Servicios**

Crear la interfase y la implementación de la interfase similar a lo siguiente:

``` java
public interface IMiEntidadService {

    public List<MiEntidad> buscarTodos();
    public MiEntidad buscarPorId(Integer id);
    public MiEntidad guardar (MetodoDePago metodoDePago);
    public void eliminar(Integer id);
    public boolean existe(Integer id);
}
```

**Controlador**

Crear en el controlador métodos para los siguientes *actions*

  - `GET` para obtener el listado de todos los elementos.
  - `GET` para obtener un solo elemento por *id*.
  - `POST` para la creación de un nuevo elemento.
  - `PUT` para la modificación de un elemento.
  - `DELETE` para la eliminación de un elemento por su id

**Además, se debe tener en cuenta lo siguiente:**

  - *Convención de nombres:* para los nombres de los métodos en el controlador, debes incluir la referencia a su entidad (a diferencia de lo que sucede en el servicio) por ejemplo: buscarPersonaPorId.
  - *Utilidades del response*: utilizar el objeto ResponseEntity combinado con el objeto APIResponse. Utilizar la utilidad ResponseUtil.
  - *Manejo de excepciones*: añadir el manejo de excepciones utilizando la utilidad del ResponseUtil

**Como tarea adicional, se requiere lo siguiente:**

  - Crear una documentación (de código comentado) explicando y detallando lo mejor posible el funcionamiento técnico de la siguiente parte del código:

*En el controlador, documenta con comentarios el método `GET` para obtener un solo elemento por id.*

  - Probar todos los métodos del controlador y hacer captura de pantalla de la evidencia obtenida. Esta evidencia debe ser incluida en los comentarios del pull request.

**Recuerda que la primera entrega de la tarea es el 16 de Octubre y la entrega final el 23 de Octubre**

**Comment by EmilianoBarroso** [comment]
Probando los métodos del Controlador:
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/1b39ff28-73d0-4b5f-bb2d-0761e4528104)
GET para obtener el listado de todos los elementos.

**Comment by EmilianoBarroso** [comment]
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/bf4f6886-6bfe-45c8-90a8-a777fbbb7dbb)

**Comment by EmilianoBarroso** [comment]
GET para obtener un solo elemento por id.
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/9d518ef3-6371-49f5-aaa2-d1bf82079477)
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/88062b78-ce53-46fc-af4e-a445831fa8a7)

**Comment by EmilianoBarroso** [comment]
PUT para la modificación de un elemento.
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/cb4ea989-a8d6-4cb1-bd17-9fd608678622)

**Comment by EmilianoBarroso** [comment]
DELETE para la eliminación de un elemento por su id
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/ab78ad60-df88-452f-9cfd-5ea78c1431cf)
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/bbdd063b-a1f5-4073-98d7-ee9169c32a03)

**Comment by EmilianoBarroso** [comment]
POST para la creación de un nuevo elemento.
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/57a2ff34-54e3-43d7-9e81-fbabf2ff6dc3)
![image](https://github.com/ahumadamob/turnero2023spring/assets/90419197/3acf6d29-67bb-4115-b307-cd71b9e2b1dc)
