### ISSUE TITLE
Mejoras en la entidad: Sala

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/turnero2023spring#39]
**Entidad**

Verificar que en tu entidad asignada tenga las relaciones `@ManyToOne` correspondientes

**Servicios**

Crear la interfase y la implementación de la interfase similar a lo siguiente:

``` java
public interface IMiEntidadService {

    public List<MiEntidad> buscarTodos();
    public MiEntidad buscarPorId(Integer id);
    public MiEntidad guardar (MetodoDePago metodoDePago);
    public void eliminar(Integer id);
    public boolean existe(Integer id);
}
```

**Controlador**

Crear en el controlador métodos para los siguientes *actions*

  - `GET` para obtener el listado de todos los elementos.
  - `GET` para obtener un solo elemento por *id*.
  - `POST` para la creación de un nuevo elemento.
  - `PUT` para la modificación de un elemento.
  - `DELETE` para la eliminación de un elemento por su id

**Además, se debe tener en cuenta lo siguiente:**

  - *Convención de nombres:* para los nombres de los métodos en el controlador, debes incluir la referencia a su entidad (a diferencia de lo que sucede en el servicio) por ejemplo: buscarPersonaPorId.
  - *Utilidades del response*: utilizar el objeto ResponseEntity combinado con el objeto APIResponse. Utilizar la utilidad ResponseUtil.
  - *Manejo de excepciones*: añadir el manejo de excepciones utilizando la utilidad del ResponseUtil

**Como tarea adicional, se requiere lo siguiente:**

  - Crear una documentación (de código comentado) explicando y detallando lo mejor posible el funcionamiento técnico de la siguiente parte del código:

*En el controlador, documenta con comentarios el método `PUT` para la modificación de un elemento.*

  - Probar todos los métodos del controlador y hacer captura de pantalla de la evidencia obtenida. Esta evidencia debe ser incluida en los comentarios del pull request.

**Recuerda que la primera entrega de la tarea es el 16 de Octubre y la entrega final el 23 de Octubre**

**Comment by facuEgarrat** [comment]
Buenas tardes profe! Como esta? A continuación adjunto las validaciones correspondientes de todos los métodos del controlador:

![image](https://github.com/ahumadamob/turnero2023spring/assets/136384242/3963820e-a22c-415a-9c89-ec14a2ecf5d4)

![image](https://github.com/ahumadamob/turnero2023spring/assets/136384242/5fb74fb6-1b0a-4d0a-a594-282cc06dc563)

![image](https://github.com/ahumadamob/turnero2023spring/assets/136384242/0310b39a-a1e1-4da4-8205-580073c2ebf8)

![image](https://github.com/ahumadamob/turnero2023spring/assets/136384242/b299a1b4-08e8-47f0-8c30-71cd63d1e5d8)

![image](https://github.com/ahumadamob/turnero2023spring/assets/136384242/c73e72ff-e98c-46bd-a4be-ca9095905d78)

![image](https://github.com/ahumadamob/turnero2023spring/assets/136384242/23b7269c-2300-46fe-95d4-889e3746227e)

![image](https://github.com/ahumadamob/turnero2023spring/assets/136384242/c21ddd6d-3c77-451d-8dd7-0fbea8e228fc)
