### ISSUE TITLE
Mejoras en la entidad: Turno

### ISSUE THREAD

**Issue by ahumadamob** [ahumadamob/turnero2023spring#40]
**Entidad**

Verificar que en tu entidad asignada tenga las relaciones `@ManyToOne` correspondientes

**Servicios**

Crear la interfase y la implementación de la interfase similar a lo siguiente:

``` java
public interface IMiEntidadService {

    public List<MiEntidad> buscarTodos();
    public MiEntidad buscarPorId(Integer id);
    public MiEntidad guardar (MetodoDePago metodoDePago);
    public void eliminar(Integer id);
    public boolean existe(Integer id);
}
```

**Controlador**

Crear en el controlador métodos para los siguientes *actions*

  - `GET` para obtener el listado de todos los elementos.
  - `GET` para obtener un solo elemento por *id*.
  - `POST` para la creación de un nuevo elemento.
  - `PUT` para la modificación de un elemento.
  - `DELETE` para la eliminación de un elemento por su id

**Además, se debe tener en cuenta lo siguiente:**

  - *Convención de nombres:* para los nombres de los métodos en el controlador, debes incluir la referencia a su entidad (a diferencia de lo que sucede en el servicio) por ejemplo: buscarPersonaPorId.
  - *Utilidades del response*: utilizar el objeto ResponseEntity combinado con el objeto APIResponse. Utilizar la utilidad ResponseUtil.
  - *Manejo de excepciones*: añadir el manejo de excepciones utilizando la utilidad del ResponseUtil

**Como tarea adicional, se requiere lo siguiente:**

  - Crear una documentación (de código comentado) explicando y detallando lo mejor posible el funcionamiento técnico de la siguiente parte del código:

*En el controlador, documenta con comentarios el método `DELETE` para la eliminación de un elemento por su id*

  - Probar todos los métodos del controlador y hacer captura de pantalla de la evidencia obtenida. Esta evidencia debe ser incluida en los comentarios del pull request.

**Recuerda que la primera entrega de la tarea es el 16 de Octubre y la entrega final el 23 de Octubre**

**Comment by ahumadamob** [comment]
Hola Ramiro. Muy buen trabajo hasta ahora.
Es correcta la manera en la que sobrecargaste el método una vez que detectaste esta necesidad. Está muy bueno que hayas utilizado plenamente uno de los principios de la POO.
Las entidades que modificaste, está bien que lo hayas hecho para hacer funcionar tu código. Pero no la vamos a incluir en este commit (lo vamos a retirar luego) porque hay otros programadores trabajando en ello y va por aquel lado la responsabilidad de completarlo.
**Por favor, haz la siguiente prueba:**
En el llamado `PUT` intenta enviar un id vacío para ver qué sucede

**Comment by RamiroGarro** [comment]
Buenas tardes profesor.
Muchas gracias por la devolución, tendré en cuenta todo lo que me dice.
Con respecto a las entidades que modifiqué y que no las vamos a incluir en el commit, ¿tengo que modificarlo yo o usted puede ignorar la modificación de esos archivos a la hora de aceptar los cambios?
Con respecto a la prueba con el PUT la realicé y descubrí que me arrojaba el siguiente error: 
![put3error](https://github.com/ahumadamob/turnero2023spring/assets/129986175/484208e9-36da-4e3c-aade-e1d22e880ba4)
Esto se debe a que no había tenido en cuenta la posibilidad de que no se ingresara un id a través del body.
Para solucionarlo modifiqué el método PUT agregándole unos condicionales y pude lograr que ahora me arrojara un mensaje de error pidiendo que se ingrese el id:
![put3](https://github.com/ahumadamob/turnero2023spring/assets/129986175/ac7ca5a7-4e83-45bb-9b5b-29e0491d8dc8)
Espero su respuesta para ver si está bien realizado. 
Saludos!

**Comment by RamiroGarro** [comment]
Buenas tardes profesor.
Me di cuenta de dos errores a la hora de arrojar el status en los métodos PUT y DELETE del controlador. Arrojaba error 400 cuando no encontraba un Turno con el ID determinado pero tendría que haber arrojado un error 404 al no haberlo encontrado.
Adjunto nuevas pruebas en Postman de esos métodos:
<img width="867" alt="delete404" src="https://github.com/ahumadamob/turnero2023spring/assets/129986175/0dae9c4c-6086-494c-9ffa-3acf5bc462ae">
<img width="862" alt="put404" src="https://github.com/ahumadamob/turnero2023spring/assets/129986175/8cdbc7b8-46b2-4d84-9611-282fd14d7da6">
